import type { Member2WhisperSegment, Member2PipelineResult } from '../types/audioSpeech';
import type { LessonData, TranscriptSegment, CaptionItem } from '../types/lesson';

/**
 * Member 2 Audio & Speech Integration Service Boundary.
 * 
 * Provides transformation helpers and network API boundary between Member 2
 * Python pipeline endpoint and EquiLearn React frontend models.
 */

export const API_BASE_URL = 'http://localhost:8000';

/**
 * Formats time in seconds to MM:SS display format.
 */
export function formatSecondsToTimestamp(seconds: number): string {
  if (seconds < 0) seconds = 0;
  const mins = Math.floor(seconds / 60);
  const secs = Math.floor(seconds % 60);
  return `${mins.toString().padStart(2, '0')}:${secs.toString().padStart(2, '0')}`;
}

/**
 * Converts Member 2 Whisper segment list into frontend TranscriptSegment models.
 */
export function adaptMember2SegmentsToTranscript(
  segments: Member2WhisperSegment[]
): TranscriptSegment[] {
  if (!segments || !Array.isArray(segments)) return [];

  return segments.map((seg, idx) => ({
    id: `m2-seg-${idx}`,
    startTime: seg.start,
    timestamp: formatSecondsToTimestamp(seg.start),
    text: seg.text,
  }));
}

/**
 * Converts Member 2 Whisper segment list into frontend CaptionItem models.
 */
export function adaptMember2SegmentsToCaptions(
  segments: Member2WhisperSegment[]
): CaptionItem[] {
  if (!segments || !Array.isArray(segments)) return [];

  return segments.map((seg, idx) => ({
    id: `m2-cap-${idx}`,
    startTime: seg.start,
    endTime: seg.end,
    text: seg.text,
  }));
}

/**
 * Transforms Member 2 pipeline output into frontend LessonData model.
 */
export function convertMember2ResultToLessonData(
  file: File,
  result: Member2PipelineResult
): LessonData {
  const transcriptSegments = adaptMember2SegmentsToTranscript(result.asrResult.segments);
  const captionItems = adaptMember2SegmentsToCaptions(result.asrResult.segments);

  const lastSeg = result.asrResult.segments[result.asrResult.segments.length - 1];
  const totalDuration = lastSeg ? Math.ceil(lastSeg.end) : 60;

  return {
    id: `m2-lesson-${Date.now()}`,
    title: file.name,
    subject: `Member 2 Audio & Speech AI`,
    lessonNumber: 1,
    totalLessons: 1,
    content: {
      heading: `Transcript & Audio: ${file.name}`,
      sectionHeading: `AI Processed Speech (${(result.asrResult.language || 'en').toUpperCase()})`,
      paragraph: result.asrResult.text || 'Transcript generated by Member 2 Whisper speech-to-text pipeline.',
      keyConceptTitle: 'Member 2 Audio-Speech Pipeline Summary',
      keyConceptText: `Whisper ASR extracted ${result.asrResult.segments.length} timestamped segments. Text-To-Speech narration generated via gTTS.`,
    },
    audio: {
      title: `TTS Audio Narration - ${file.name}`,
      duration: totalDuration,
      formattedDuration: formatSecondsToTimestamp(totalDuration),
      src: result.ttsAudioUrl,
    },
    transcript: transcriptSegments,
    captions: captionItems,
  };
}

/**
 * Real API integration boundary function.
 * Sends uploaded File to Member 2 FastAPI backend: POST /api/v1/process-audio-speech
 */
export async function processAudioSpeechApi(
  file: File,
  targetLanguage: string = 'en'
): Promise<Member2PipelineResult> {
  const formData = new FormData();
  formData.append('file', file);
  formData.append('target_language', targetLanguage);

  const response = await fetch(`${API_BASE_URL}/api/v1/process-audio-speech`, {
    method: 'POST',
    body: formData,
  });

  if (!response.ok) {
    const errorData = await response.json().catch(() => ({ detail: response.statusText }));
    throw new Error(errorData.detail || `Server error: ${response.status}`);
  }

  const data = await response.json();

  return {
    asrResult: {
      text: data.rawTranscript || '',
      language: data.language || targetLanguage,
      segments: data.segments || [],
    },
    vttContent: data.vttUrl ? `${API_BASE_URL}${data.vttUrl}` : '',
    ttsAudioUrl: data.ttsAudioUrl ? `${API_BASE_URL}${data.ttsAudioUrl}` : undefined,
  };
}
